theme = "congo"

baseURL = "https://ebourgess.dev/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 0
enableGitInfo = true

[outputs]
  home = ["HTML", "RSS", "JSON"]