languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "eBourgess"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  description = "DevSecOps Engineer blogs about coding, life and other stuff"

[params.author]
  name = "Elias Bourgess"
  image = "images/me.jpg"
  headline = "DevSecOps Engineer"
  bio = "DevSecOps Engineer, Tech Enthusiast, Lifelong Learner, Geek"
  links = [
    { email = "mailto:elias@ebourgess.dev" },
    { github = "https://github.com/ebourgess" },
    { linkedin = "https://linkedin.com/in/ebourgess" },
  ]
