languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "eBourgess"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  description = "DevOps Engineer blogs about coding, life and other stuff"

[params.author]
  name = "Elias Bourgess"
  image = "images/me.jpg"
  headline = "DevOps Engineer"
  bio = "DevOps Engineer with 9 years of experience in the field, blogs about coding, life and other stuff"
  links = [
    { email = "mailto:elias@ebourgess.dev" },
    { github = "https://github.com/ebourgess" },
    { linkedin = "https://linkedin.com/in/ebourgess" },
    { mastodon = "https://infosec.exchange/@ebourgess" },
    { x-twitter = "https://twitter.com/ebourgess" },
  ]
