[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

# [[main]]
#   name = "About"
#   pageRef = "about"
#   weight = 20

# [[main]]
#   identifier = "search"
#   weight = 99
#   [main.params]
#     action = "search"

[[main]]
  identifier = "appearance"
  weight = 100
  [main.params]
    action = "appearance"

