baseURL: 'https://ebourgess.github.io'
languageCode: 'en-us'
title: 'eBourgess'
description: 'DevOps Engineer writing about coding, life and other stuff'
theme:  'github.com/Mitrichius/hugo-theme-anubis'
pagingate: 10
enableRobotsTXT: true

menu: 
  main: 
    - identifier: archive
      title: Blog
      name: Blog
      url: /posts/
      weight: 0
    - identifier:  about
      name: About
      url: /about/
      weight: 0

params:
  author: 'eBourgess'
  email: elias@ebourgess.dev
  avatar: './images/me.jpg'
  description: 'DevOps Engineer writing about coding, life and other stuff'
  dateFormat: '2006-01-02'
  paginationSinglePost: true
  style: auto
  readMore: true
  readNextPosts: 3
  disableSummary: false
  copyCodeButton: true
  rssAsSocialIcons: true

  social:
  - id: github
    url: 'https://github.com/ebourgess'
  - id: mastodon
    url: 'https://infosec.exchange/web/@ebourgess'
  - id: linkedin
    url: 'https://www.linkedin.com/in/ebourgess/'
  - id: twitter
    url: 'https://twitter.com/ebourgess'

